# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('hostname', models.CharField(max_length=80)),
            ],
        ),
    ]
